### ISSUE TITLE
PrettyBreaks ?

### ISSUE THREAD

**Issue by mthh** [riatelab/statsbreaks#14]
Should we add *Pretty Breaks* ?

They are breaks that are equally spaced round values which cover the range of values in the input array.
The breaks are chosen so that they are 1, 2, or 5 times a power of 10 (such breaks could for example be `300.00,  2000.00,  4000.00, 6000.00, 8000.00, 10000.00`)

This method is available in *mapclassify* Python package and in *classInt* R package.

**Comment by mthh** [comment]
Example implementation : https://github.com/mthh/statsbreaks/commit/9fd8dbe13747e0ab061157b46ce4bfec47435b88

**Comment by neocarto** [comment]
Good idea. Go :-)
