### ISSUE TITLE
Data filtering

### ISSUE THREAD

**Issue by mthh** [riatelab/statsbreaks#2]
While working on updating Magrit's classification panel I gave a look at `statsbreaks`.

In each classification method, you're filtering the data and converting it to numbers by using

```js
data = data.filter((d) => d != "").map((x) => +x)
```

Doing this filters out the `0` values (compared to using `d !== ""` which doesn't), is it intended ?

A quick fix could just be to use `data = data.filter((d) => d !== "").map((x) => +x)`
However, it still doesn't filter out `NaN` or `Infinity`.

A better way to filter the values might be to check if all the values are finite with [Number.isFinite](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite) or [isFinite](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/isFinite) (they have a slightly different behavior - the second one also returns `true` for strings that can be converted to number).

So maybe:
```js
data = data.filter((d) => isFinite(d)).map((x) => +x)
```

**Comment by neocarto** [comment]
I think you're right. My bad. Feel free to suggest a PR if you have time. Tell me.
And what a good idea tu use statsbreaks in Magrit if it's relevant for you. Note that the jenks method comes from your code (https://github.com/riatelab/magrit/blob/master/client/js/webworker_jenks.js)

**Comment by mthh** [comment]
I'm precisely about to submit a PR about Jenks ;)
