### ISSUE TITLE
minmax slice option applied twice with headtail

### ISSUE THREAD

**Issue by TomBor** [riatelab/statsbreaks#20]
There is duplicate code in the [headtail method](https://github.com/riatelab/statsbreaks/blob/main/src/method-headtail.js#L58) that result in four values sliced instead of two when minmax option is chosen.

**Comment by mthh** [comment]
Good catch !

**Comment by mthh** [comment]
Thank you! I proposed a fix.

We recently added a (work in progress) test suite to *statsbreaks*, I'll add a test in a future PR to test that this doesn't happen again, on headtail and also on the other methods.

**Comment by neocarto** [comment]
Thanks Thomas
