### ISSUE TITLE
add a method to return values split by breaks

### ISSUE THREAD

**Issue by TomBor** [riatelab/statsbreaks#24]
To go further than `getCountByClass` method, there could be a method to split values in cluster by breaks.

For example, from a series of values [1,2,3,4,5,6,7,8,9,10] and three breaks [3,6,8] we get a new array :
```js
[
   [1,2,3], // first class
   [4,5,6], // second class
   [7,8],
   [9,10],
]
```

**Why?**  
Maybe there is some use cases where you need this kind of data structure.

**Comment by mthh** [comment]
Yeah that's also a classic functionality so I guess it's a good idea (I think `mapclassify` Python library propose such a feature for example).

**Comment by TomBor** [comment]
I explored two approaches of splitting an array by breaks in this notebook: https://observablehq.com/d/42a6ec529595b3bc

A simple one with just `Array.filter()` and a more complex one by finding the closest index value of a break in a series of value.
The second approach is faster, but do we need all that code for a non essential helper method?

**Comment by mthh** [comment]
Thanks for the comparison :+1: 

Looking at your notebook, I get the feeling that method n°1, with `filter`, is fast enough (and easier to understand) not to bother with method n°2.

But I'll leave it to @neocarto to decide.

**Comment by neocarto** [comment]
Agree with @mthh. And I think it's a good idea too. PR @TomBor ?

**Comment by TomBor** [comment]
Good! Yes, I can prepare a PR.
