### ISSUE TITLE
behavior of number of classes option

### ISSUE THREAD

**Issue by TomBor** [riatelab/statsbreaks#25]
There is a need to unify what each discretization method return with weird "nb" option.
Since v1, some cases are handled with a default number of classes and an error message for higher breaks than values.
But there is still cases who need unification.

**When `nb` is...**
+ a floating number => strange result with all methods
+ 1 => does it makes sense to run a method if we knows from start that it should return `[min, max]` or an empty array with `minmax: false` option. Why not intercept this case before running a discretization.
+ 0 => is there a reason to allow it? Return default nb=5 or an error message?

**Comment by mthh** [comment]
Indeed I think we should return an Error (with an explicit message) when:
- nb == 0
- nb is a floating-point number or anything else than an integer ~~(currently, using a string returns "TooFewValuesError" which isn't helpful for the user)~~

I'm not sure about nb == 1. What do you think @neocarto ?

**Comment by mthh** [comment]
@TomBor @neocarto, do any of you intend to make this contribution?
If not, I volunteer to do so (in which case would it be OK for you @TomBor to review it?).

**Comment by neocarto** [comment]
Ok for me. Thanks @mthh

**Comment by TomBor** [comment]
@mthh I'm fine with reviewing your contribution!
