### ISSUE TITLE
Unexpected results with `splitByClass`

### ISSUE THREAD

**Issue by mthh** [riatelab/statsbreaks#37]
The `splitByClass` method seems to return wrong results (or I don't understand what it's supposed to return).

Specifically, it doesn't return the same number of groups as there are classes (and some values appear in more than one group).

Example: https://observablehq.com/d/e3245d6af2a7571d

cc @TomBor

**Comment by TomBor** [comment]
Well, you have been quicker into fixing the problem and with a shorter function 👏

**Comment by mthh** [comment]
Well, I only extracted it from another project I'm working on :smile:
