### ISSUE TITLE
different rounding for min and max

### ISSUE THREAD

**Issue by TomBor** [riatelab/statsbreaks#9]
By applying the same rounding method to each breaks including min and max, it can potentially result in a rounding min or max that is excluding the real min or max of the values.

Considering this example and a precision of 2
```js
const realMin = 1.006
const roundingMin = realMin.toFixed(2) // "1.01"

const realMax = 9.004
const roundingMax = realMax.toFixed(2) // "9.00"
```

Depending of the usage of the rounding min/max, it can be harmless (like in a legend) or not.

In addition, Number.toFixed present some issue: `1.255.toFixed(2)` return "1.25" instead of "1.26"

A possible solution could be to use `Math.floor` for min and `Math.ceil` for max. But it need another approach of rounding that the one use in rounding.js

First an equivalent and more precise version of rounding function in rounding.js is:
```js
// Borrow from Amr Ali in https://stackoverflow.com/a/48764436
function round(number, precision) {
  const p = Math.pow(10, precision);
  const n = number * p * (1 + Number.EPSILON);
  return Math.round(n) / p;
}
```
Same principle for floor and ceil:
```js
// Still borrow from Amr Ali in  https://stackoverflow.com/a/48764436
function floor(number, precision) {
  const p = Math.pow(10, precision);
  const n = number * p * (1 + Math.sign(number) * Number.EPSILON);
  return Math.floor(n) / p;
}

function ceil(number, precision) {
  const p = Math.pow(10, precision);
  const n = number * p * (1 - Math.sign(number) * Number.EPSILON);
  return Math.ceil(n) / p;
}
```

We can then apply the right rounding function based on breaks position: first break (min) => `floor`, last break (max) => `ceil`, rest => `round`

I can make a pull request to implement this approach

**Comment by neocarto** [comment]
Thanks Thomas. I'll include it in the next version.
